// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3pmrEVZN9nCLgsGePb7WNpo1LdZYK0Gw',
    appId: '1:777404274351:web:422202e56b91cfc487265a',
    messagingSenderId: '777404274351',
    projectId: 'taksis-754a6',
    authDomain: 'taksis-754a6.firebaseapp.com',
    storageBucket: 'taksis-754a6.firebasestorage.app',
    measurementId: 'G-4P3MHTTT9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8y80kQglVO4J6vkS3gZScMppY3s8M8ik',
    appId: '1:777404274351:android:e720f0c3406c016e87265a',
    messagingSenderId: '777404274351',
    projectId: 'taksis-754a6',
    storageBucket: 'taksis-754a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS5szTjPM52RzBPqGlefkawsAT1Hj6Lb4',
    appId: '1:777404274351:ios:8d912ef2f18d05af87265a',
    messagingSenderId: '777404274351',
    projectId: 'taksis-754a6',
    storageBucket: 'taksis-754a6.firebasestorage.app',
    iosBundleId: 'com.taksis.user',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3pmrEVZN9nCLgsGePb7WNpo1LdZYK0Gw',
    appId: '1:777404274351:web:87c0d8d96de1579887265a',
    messagingSenderId: '777404274351',
    projectId: 'taksis-754a6',
    authDomain: 'taksis-754a6.firebaseapp.com',
    storageBucket: 'taksis-754a6.firebasestorage.app',
    measurementId: 'G-D4FHH2MLJ1',
  );

}