// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqonBA6eMk-_JHx7B5yjdI8Bbf2yT_Ufo',
    appId: '1:196955145329:web:c3ba3395d9d27a521087d0',
    messagingSenderId: '196955145329',
    projectId: 'taksis-4e8ff',
    authDomain: 'taksis-4e8ff.firebaseapp.com',
    storageBucket: 'taksis-4e8ff.firebasestorage.app',
    measurementId: 'G-68JH5B7Z54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSudZQ_3_HOWD9mbdxCODY6VQBIEakTyc',
    appId: '1:196955145329:android:6e0b4be6cd57acae1087d0',
    messagingSenderId: '196955145329',
    projectId: 'taksis-4e8ff',
    storageBucket: 'taksis-4e8ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkOawH2kV5NomDd0PH9Gv-nTaP2De47po',
    appId: '1:196955145329:ios:c5d78eb62b5789391087d0',
    messagingSenderId: '196955145329',
    projectId: 'taksis-4e8ff',
    storageBucket: 'taksis-4e8ff.firebasestorage.app',
    iosBundleId: 'com.taksis.user.taksis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqonBA6eMk-_JHx7B5yjdI8Bbf2yT_Ufo',
    appId: '1:196955145329:web:c813040a13d063fc1087d0',
    messagingSenderId: '196955145329',
    projectId: 'taksis-4e8ff',
    authDomain: 'taksis-4e8ff.firebaseapp.com',
    storageBucket: 'taksis-4e8ff.firebasestorage.app',
    measurementId: 'G-GFD5KMNJB9',
  );
}
