import 'models/Product.dart';

List<Product> bagProducts = [
  Product(
      ["assets/images/products/product1.png"],
      'Women Printed Kurta',
      "Neque porro quisquam est qui dolorem ipsum quia",
      "Neque porro quisquam est qui dolorem ipsum quia",
      2499,
      40,
      56890,
      4),
  Product(
      ["assets/images/products/product2.png"],
      'HRX by Hrithik Roshan',
      "Neque porro quisquam est qui dolorem ipsum quia",
      "Neque porro quisquam est qui dolorem ipsum quia",
      4999,
      50,
      344567,
      4.5),
  Product(
      ["assets/images/products/product3.png"],
      'Philips BHH880/10',
      "Hair Straightening Brush With Keratin Infused Bristles (Black).",
      "Hair Straightening Brush With Keratin Infused Bristles (Black).",
      1999,
      50,
      646776,
      3.5),
  Product(
      ["assets/images/products/product4.png"],
      'TITAN Men Watch- 1806N',
      "This Titan watch in Black color is I wanted to buy for a long time",
      "This Titan watch in Black color is I wanted to buy for a long time",
      3500,
      60,
      15007,
      5),
  Product(
      ["assets/images/products/product5.png"],
      'IWC Schaffhausen',
      "2021 Pilot's Watch \"SIHH 2019\" 44mm",
      "2021 Pilot's Watch \"SIHH 2019\" 44mm",
      1599,
      60,
      56890,
      4),
  Product(
      ["assets/images/products/product6.png"],
      'HRX by Hrithik Roshan',
      "Neque porro quisquam est qui dolorem ipsum quia",
      "Neque porro quisquam est qui dolorem ipsum quia",
      4999,
      50,
      344567,
      4.5),
  Product(
      ["assets/images/products/product7.png"],
      'Philips BHH880/10',
      "Hair Straightening Brush With Keratin Infused Bristles (Black).",
      "Hair Straightening Brush With Keratin Infused Bristles (Black).",
      1999,
      50,
      646776,
      3.5),
  Product(
      ["assets/images/products/product8.png"],
      'TITAN Men Watch- 1806N',
      "This Titan watch in Black color is I wanted to buy for a long time",
      "This Titan watch in Black color is I wanted to buy for a long time",
      3500,
      60,
      15007,
      5),
  Product(
      ["assets/images/products/product9.png"],
      'TITAN Men Watch- 1806N',
      "This Titan watch in Black color is I wanted to buy for a long time",
      "This Titan watch in Black color is I wanted to buy for a long time",
      3500,
      60,
      15007,
      5),
];

List<Product> productsList = [
  Product(
      ["assets/images/products/product1.png"],
      'Women Printed Kurta',
      "Neque porro quisquam est qui dolorem ipsum quia",
      "Neque porro quisquam est qui dolorem ipsum quia",
      2499,
      40,
      56890,
      4),
  Product(
      ["assets/images/products/product2.png"],
      'HRX by Hrithik Roshan',
      "Neque porro quisquam est qui dolorem ipsum quia",
      "Neque porro quisquam est qui dolorem ipsum quia",
      4999,
      50,
      344567,
      4.5),
  Product(
      ["assets/images/products/product3.png"],
      'Philips BHH880/10',
      "Hair Straightening Brush With Keratin Infused Bristles (Black).",
      "Hair Straightening Brush With Keratin Infused Bristles (Black).",
      1999,
      50,
      646776,
      3.5),
  Product(
      ["assets/images/products/product4.png"],
      'TITAN Men Watch- 1806N',
      "This Titan watch in Black color is I wanted to buy for a long time",
      "This Titan watch in Black color is I wanted to buy for a long time",
      3500,
      60,
      15007,
      5),
  Product(
      ["assets/images/products/product5.png"],
      'IWC Schaffhausen',
      "2021 Pilot's Watch \"SIHH 2019\" 44mm",
      "2021 Pilot's Watch \"SIHH 2019\" 44mm",
      1599,
      60,
      56890,
      4),
  Product(
      ["assets/images/products/product6.png"],
      'HRX by Hrithik Roshan',
      "Neque porro quisquam est qui dolorem ipsum quia",
      "Neque porro quisquam est qui dolorem ipsum quia",
      4999,
      50,
      344567,
      4.5),
  Product(
      ["assets/images/products/product7.png"],
      'Philips BHH880/10',
      "Hair Straightening Brush With Keratin Infused Bristles (Black).",
      "Hair Straightening Brush With Keratin Infused Bristles (Black).",
      1999,
      50,
      646776,
      3.5),
  Product(
      ["assets/images/products/product8.png"],
      'TITAN Men Watch- 1806N',
      "This Titan watch in Black color is I wanted to buy for a long time",
      "This Titan watch in Black color is I wanted to buy for a long time",
      3500,
      60,
      15007,
      5),
  Product(
      ["assets/images/products/product9.png"],
      'TITAN Men Watch- 1806N',
      "This Titan watch in Black color is I wanted to buy for a long time",
      "This Titan watch in Black color is I wanted to buy for a long time",
      3500,
      60,
      15007,
      5),
];

List<String> productImages = [
  'assets/images/products/product1.png',
  'assets/images/products/product2.png',
  'assets/images/products/product3.png',
  'assets/images/products/product4.png',
  'assets/images/products/product5.png',
  'assets/images/products/product6.png',
  'assets/images/products/product7.png',
  'assets/images/products/product8.png',
  'assets/images/products/product9.png',
];

Product product = Product(productImages, 'IWC Schaffhausen',
    "2021 Pilot's Watch \"SIHH 2019\" 44mm","Perhaps the most iconic sneaker of all-time, this original \"Chicago\"? colorway is the cornerstone to any sneaker collection. Made famous in 1985 by Michael Jordan, the shoe has stood the test of time, becoming the most famous colorway of the Air Jordan 1. This 2015 release saw the", 1599, 60, 56890, 4);
